### ISSUE TITLE
リッチテキストに画像が含まれているとres.buffer is not a functionが発生する

### ISSUE THREAD

**Issue by kefi3104** [dc7290/microcms-richedit-processer#192]
**Describe the bug**
Draftページやローカル開発の際に、下記の行で表題のエラーが発生しています。
node-fetchで取得したレスポンスに対してbuffer()が存在しないケースがあるようです。
https://github.com/dc7290/microcms-richedit-processer/blob/43573f92d9206865af0cc56183d00f63db74980b/src/processers/img.ts#L30

以下のように修正したら正常に動作しました。
```
  const size = sizeOf(
      await fetch(splitSrc[0])
          .then((res) => res.arrayBuffer())
          .then(arrayBuffer => Buffer.from(arrayBuffer))
  )
```

**To Reproduce**
- 画像が含まれているフィールドをprocesserで処理しているページにリンク経由で遷移する。

**Expected behavior**
正常に画面が表示される

**Screenshots**
![image](https://user-images.githubusercontent.com/3159281/208289734-6a379a7c-3f05-4f0d-99af-b94cb9c9ab5d.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 
 - Version: 108.0.5359.124 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dc7290** [comment]
Issueの投稿ありがとうございます！
すみません、全く気づいておりませんでした🙇‍♂️

動作の確認をしたのちまた連絡しますね！
